const R = {
  string: {
    taxi: "تاکسی",
    van: "ون",
    delivery: "پیک",
    bike: "موتور",
    free: "آزاد",
    on_mission: "در ماموریت",
    inactive: "غیر فعال",
    active: "فعال",
    suspended: "مسدود شده",
    hidden: "مخفی",
    taxi_service: "تاکسی سرویس",
    cargo_service: "باربری",
    count: "تعداد",
    kilo: "کیلو",
    pending: "در انتظار",
    cancel_by_user: "لغو توسط کاربر",
    reject_by_admin: "رد توسط مدیر",
    reject_by_operator: "رد توسط اپراتور",
    confirm_by_admin: "تایید مدیر",
    confirmed: "تایید شده",
    rejected: "رد شده",
    seen: "خوانده شده",
    seen_by_admin: "خوانده شده توسط مدیر",
    seen_by_operator: "خوانده شده توسط اپراتور",
    assigned: "اختصاص یافته",
    draft: "پیش نویس",
    done: "پایان یافته",
    on_route: "در مسیر",
    ready: "آماده",
    published: "منتشر شده",
    mission_status_update: "تغییر وضعیت ماموریت",
    request_status_update: "تغییر وضعیت سرویس",
    request_driver_location_update: "تغییر موقعیت راننده",
  },
};

module.exports = R;
